apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-web
  template:
    metadata:
      labels:
        io.kompose.service: nginx-web
    spec:
      containers:
        - image: ghcr.io/hblok/ct_nginx_web:{{.Values.nginx_web_version}}
          name: nginx-web
          imagePullPolicy: Always
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      hostname: nginx-web
status: {}
