version: "3.3"

services:
  travel_grpc:
    container_name: travel_grpc
    image: "ghcr.io/hblok/ct_travel_server:latest"
    networks:
      - travel
      
  nginx_web:
    container_name: nginx_web
    image: "ghcr.io/hblok/ct_nginx_web:latest"
    networks:
      - travel
      
  envoy_proxy:
    image: "ghcr.io/hblok/ct_envoy_distroless:v1.32"
    networks:
      - travel
    ports:
      - 12000:12000
    labels:
      kompose.service.type: LoadBalancer 


networks:
  travel:
    driver: bridge

