apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloud
resources:
  - envoy-proxy-deployment.yaml
  - envoy-proxy-service.yaml
  - nginx-web-deployment.yaml
  - nginx-web-service.yaml
  - travel-grpc-deployment.yaml
  - travel-grpc-service.yaml
  - travel-networkpolicy.yaml
labels:
  - includeSelectors: true
    pairs:
      app: cloud-tycoon
