services:
  travel_grpc:
    container_name: travel_grpc
    image: "travel_server:latest"
    networks:
      - travel
      
  nginx_web:
    container_name: nginx_web
    image: "nginx_web:latest"
    networks:
      - travel
      
  envoy_proxy:
    image: "envoy_distroless:v1.32"
    networks:
      - travel
    ports:
      - 12000:12000


networks:
  travel:
    driver: bridge

