services:
  travel-grpc:
    container_name: travel-grpc
    image: "travel_server:latest"
    networks:
      - travel
      
  nginx-web:
    container_name: nginx-web
    image: "nginx_web:latest"
    networks:
      - travel
      
  envoy-proxy:
    image: "envoy_distroless:v1.32"
    networks:
      - travel
    ports:
      - 12000:12000


networks:
  travel:
    driver: bridge

