- hosts: aws
  remote_user: admin
  vars:     
    ansible_ssh_private_key_file: "/root/aws_key.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Apt install
      ansible.builtin.apt:
        pkg:
          - htop
          - emacs-nox
          - docker-ce
        state: latest

    - name: Add user to docker group
      ansible.builtin.user:
        name: admin
        groups: docker
        append: yes

  become: true
