- hosts: azure
  remote_user: tstuser
  vars:     
    ansible_ssh_private_key_file: "/root/azure_key.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    
  tasks:
  
  - name: mkdir travel
    ansible.builtin.file:
      path: /home/tstuser/travel
      state: directory
 
  - name: mkdir .docker
    ansible.builtin.file:
      path: /home/tstuser/.docker
      state: directory

  - name: Copy Docker conf
    ansible.builtin.copy:
      src: /docker_config.json
      dest: ~/.docker/config.json

  - name: Copy compose
    ansible.builtin.copy:
      src: /docker-compose.yml
      dest: ~/travel/docker-compose.yml

  - name: Start stack
    community.docker.docker_compose_v2:
        project_src: ~/travel
        state: present
