name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'      
      - uses: bazelbuild/setup-bazelisk@v3
        with:
          bazelisk-version: 1.22.1

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Install dependencies
        run: sudo apt-get install --allow-downgrades python3=3.11.2-1+b1
        #sudo apt-get install -y graphviz

      - name: Print versions
        run: bazel --version; python3 --version

      - name: List rules
        run: bazel query ...
        
      - name: Build
        run: bazel test --sandbox_debug --test_output all --test_tag_filters -skip //...

      - name: Test results
        run: bazel test  --test_tag_filters -skip //...

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker images to Github
        run: bazel run //docker:push_all_github
